### ISSUE TITLE
An error in “A minimal DeepArchitect example with Keras”

### ISSUE THREAD

**Issue by wxjcn** [negrinho/deep_architect#2]

**Comment by wxjcn** [comment]
hi, I‘m new in your project. When I run your example ,there is an error:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-6-8c5adb856fad> in <module>
      2 random_specify(outputs)
      3 inputs_val = Input((784,))
----> 4 co.forward({inputs["In"]: inputs_val})
      5 outputs_val = outputs["out"].val
      6 vi.draw_graph(outputs, draw_module_hyperparameter_info=False)

KeyError: 'In'
---------------------------------------------------------------------------
When I changed 'In' to 'in', the project was able to run successfully.

**Comment by negrinho** [comment]
Thanks! Great catch. The default input name for single input modules was refactored from `"In"` to `"in"`. I missed this spot. I will submit a fix right now.

`"in"` and `"out"` are the input and output names that you should expect in single-input single-output cases. If there are multiple inputs and/or outputs, we use `"in0"`, `"in1"`, and so on, and `"out0"`, `"out1"`, and so on. 

In any case, `inputs` and `outputs` are dictionaries so you can always check their keys when in doubt.

**Comment by negrinho** [comment]
Fixed by https://github.com/negrinho/deep_architect/commit/ebf27938d6659c5d6cf2d305f801bdda78288874
