### ISSUE TITLE
A issues about the enas_searcher.py

### ISSUE THREAD

**Issue by ghost** [negrinho/deep_architect#5]
hi, i am trying to run your code which is error:
deep_architect-master\dev\enas\searcher\enas_searcher.py.  
I wonder if you have the same bug. let's look at this: in **enas_searcher.py line90** 
the code is : **outputs, list(hs.values()))):**
pycharm notes : Unresolved reference 'hs' 
I sincerely hope that you can help to solve this problem. Thanks

**Comment by negrinho** [comment]
Repeat of https://github.com/negrinho/deep_architect/issues/4
